// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdhresijqxdgxgifkqgn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkaHJlc2lqcXhkZ3hnaWZrcWduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NzQ2MDcsImV4cCI6MjA2ODE1MDYwN30.Cpm_8nY92vwBWf4yx1m9rcX6guIu4Qvlyeus-TbGb8U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});